_extends: .github
repository:
  name: cypress-scaffolder
  description: opinionated scaffolder for leveraging Cypress for testing a project
  homepage: 'https://npm.im/@form8ion/cypress-scaffolder'
  private: false
